CREATE TABLE users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  userdata TEXT NOT NULL
);

CREATE TABLE albums (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  artists_ids TEXT NOT NULL,
  description TEXT,
  youtube_id TEXT
);

CREATE TABLE musics (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR NOT NULL,
  artists_ids TEXT NOT NULL,
  album_id VARCHAR NOT NULL,
  youtube_id TEXT
);

CREATE TABLE artists (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR NOT NULL,
  description TEXT,
  userdata TEXT NOT NULL
);